spring:
  application:
    name: tasktracker

  datasource:
    url: jdbc:mysql://localhost:3306/tasktracker?createDatabaseIfNotExist=true
    username: root
    password: 12345


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true